channels:
  - https://conda.ovito.org
  - conda-forge
dependencies:
  - python=3.12
  - lammps
  - numpy
  - scipy
  - matplotlib
  - xarray
  - pandas
  - numba
  - uncertainties
  - tqdm
  - conda.ovito.org:ovito